### ISSUE TITLE
Ampule download file from webserver example

### ISSUE THREAD

**Issue by cs-devansh-mahajan** [deckerego/ampule#24]
I embedded a link into the HTML page from example to download a file from the circuit python webserver but after downloading it there was a ERROR NO FILE from chrome how do I fix this ?

**Comment by deckerego** [comment]
Can you provide some code as an example, or provide steps to reproduce?

**Comment by cs-devansh-mahajan** [comment]
> Can you provide some code as an example, or provide steps to reproduce?

Never mind I managed to fix it it seems it's just google Chrome it won't work on
