### ISSUE TITLE
How to use with MicroPython?

### ISSUE THREAD

**Issue by skipfire** [deckerego/ampule#27]
I've been using Ampule with CircuitPython and love it, trying to get it to work with MicroPython and I'm stumped on the server configuration piece due to socketpool as I get `ImportError: no module named 'socketpool'`.  Can you provide any guidance on how to configure the startup of Ampule with MicroPython?

Thanks.

**Comment by deckerego** [comment]
I haven't tested Ampule with MicroPython - if it doesn't have the socketpool library then it will not work with this implementation.
