### ISSUE TITLE
Adafruit AirLift

### ISSUE THREAD

**Issue by speccy88** [deckerego/ampule#8]
Is the library compatible with Adafruit AirLift WiFi coprocessor like the Metro M4 Express AirLift?

**Comment by deckerego** [comment]
Maaaaaybe. Ampule relies heavily on the CircuitPython wifi and socketpool libraries - so if it supports CircuitPython 7 and the wifi libraries, you should be good to go.

**Comment by deckerego** [comment]
Let me know if you have any issues with the AirLift @speccy88 - I'll re-open this as an enhancement if so
